LunchBoxAdmin/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/* session Auth class. dont uses */
namespace LunchBoxAdmin.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string username, string password)
        {
            if (username != null && password != null && username.Equals("admin") && password.Equals("admin"))
            {
                HttpContext.Session.SetString("username", username);
                return View("MySite");
            }
            else
            {
                ViewBag.error = "Invalid Account";
                return View("Index");
            }
        }

        public IActionResult MySite()
        {
            return View("MySite");
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("username");
            return RedirectToAction("Index", "Home");
        }
    }
}

LunchBoxAdmin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using LunchBox.Shared;

namespace LunchBoxAdmin.Controllers
{

    [Authorize]
    public class OrderController : Controller
    {
       [HttpGet]
        public IActionResult Index()
        {
            return View(new List<Order>());
        }
    }
}

LunchBoxAdmin/Controllers/StoreController.cs
using LunchBox.Shared;
using LunchBoxAdmin.Models;
using LunchBoxAdmin.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace LunchBoxAdmin.Controllers
{
    [Authorize]
    public class StoreController : Controller
    {
        private readonly IStoreRepository storeRepository;
        private readonly IWebHostEnvironment webHostEnvironment;

        public StoreController(IStoreRepository storeRepository, IWebHostEnvironment webHostEnvironment)
        {
            this.storeRepository = storeRepository;
            this.webHostEnvironment = webHostEnvironment;
        }
        public async Task<ViewResult> Index()
        {
            var model = await storeRepository.GetStores();

            return View(model);
        }

        public async Task<ViewResult> Details(int id)
        {
            var model = await storeRepository.GetStore(id);
            if (model == null)
            {
                ViewBag.ErrorMessage = $"Store with Id = {id} cannot be found";
                return View("NotFound");
            }
            return View(model);
        }

        public ViewResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(StoreCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                String logoUniqueFileName = LogoUploadProcess(model);

                Store store = new Store
                {
                    Active = model.Active,
                    ActiveOffMes = model.ActiveOffMes,
                    ChainId = model.ChainId,
                    City = model.City,
                    Cvr = model.Cvr,
                    ContactPersonEmail = model.ContactPersonEmail,
                    ContactPersonName = model.ContactPersonName,
                    Created = DateTime.Now,
                    DeliveryOption = model.DeliveryOption,
                    Description = model.Description,
                    Discount = model.Discount,
                    Email = model.Email,
                    Pickup = model.Pickup,
                    PickupTime = model.PickupTime,
                    Logo = logoUniqueFileName,
                    Map = model.Map,
                    OpenFre = model.OpenFre,
                    OpenMan = model.OpenMan,
                    OpenSat = model.OpenSat,
                    OpenSun = model.OpenSun,
                    OpenThu = model.OpenThu,
                    OpenTue = model.OpenTue,
                    OpenWed = model.OpenWed,
                    Phone = model.Phone,
                    StoreName = model.StoreName,
                    Street = model.Street,
                    ZipCode = model.ZipCode,
                };

                await storeRepository.AddStore(store);
                return RedirectToAction("Index");
            }
            return View();
        }

        private string LogoUploadProcess(StoreCreateViewModel model)
        {
            String logoUniqueFileName = null;
            if (model.Logo != null)
            {
                if (model.Logo.FileName != null && model.Logo.Length > 0)
                {
                    String LogoPathFolder = Path.Combine(webHostEnvironment.WebRootPath, "images\\upload");
                    logoUniqueFileName = Guid.NewGuid().ToString() + "_" + model.Logo.FileName;
                    String filePath = Path.Combine(LogoPathFolder, logoUniqueFileName);

                    using var fileStream = new FileStream(filePath, FileMode.Create);
                    model.Logo.CopyTo(fileStream);
                }
            }

            return logoUniqueFileName;
        }

        public async Task<ViewResult> Edit(int id)
        {
            var result = await storeRepository.GetStore(id);
            
            StoreEditViewModel storeEditModel = new StoreEditViewModel
            {
                Id = result.Id,
                Active = result.Active,
                ActiveOffMes = result.ActiveOffMes,
                ChainId = result.ChainId,
                City = result.City,
                Cvr = result.Cvr,
                ContactPersonEmail = result.ContactPersonEmail,
                ContactPersonName = result.ContactPersonName,
                DeliveryOption = result.DeliveryOption,
                Description = result.Description,
                Discount = Convert.ToDecimal(result.Discount, new CultureInfo("fr-FR")),
                Email = result.Email,
                Pickup = result.Pickup,
                PickupTime = result.PickupTime,
                ExistingLogoPath = result.Logo,
                Map = result.Map,
                OpenFre = result.OpenFre,
                OpenMan = result.OpenMan,
                OpenSat = result.OpenSat,
                OpenSun = result.OpenSun,
                OpenThu = result.OpenThu,
                OpenTue = result.OpenTue,
                OpenWed = result.OpenWed,
                Phone = result.Phone,
                StoreName = result.StoreName,
                Street = result.Street,
                ZipCode = result.ZipCode,
            };
            return View(storeEditModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(StoreEditViewModel model)
        {
            String logoPath = null;

            if (ModelState.IsValid)
            {
                if (model.Logo != null)
                {
                    if (model.ExistingLogoPath != null)
                    {
                        String ExistingLogoPath = Path.Combine(webHostEnvironment.WebRootPath, "images\\upload", model.ExistingLogoPath);
                        if (System.IO.File.Exists(ExistingLogoPath))
                        {
                            System.IO.File.Delete(ExistingLogoPath);
                        }
                        
                    }
                    logoPath = LogoUploadProcess(model);
                }

                Store store = new Store
                {
                    Id = model.Id,
                    Active = model.Active,
                    ActiveOffMes = model.ActiveOffMes,
                    ChainId = model.ChainId,
                    City = model.City,
                    Cvr = model.Cvr,
                    ContactPersonEmail = model.ContactPersonEmail,
                    ContactPersonName = model.ContactPersonName,
                    Created = DateTime.Now,
                    DeliveryOption = model.DeliveryOption,
                    Description = model.Description,
                    Discount = model.Discount,
                    Email = model.Email,
                    Pickup = model.Pickup,
                    Logo = logoPath,
                    PickupTime = model.PickupTime,
                    Map = model.Map,
                    OpenFre = model.OpenFre,
                    OpenMan = model.OpenMan,
                    OpenSat = model.OpenSat,
                    OpenSun = model.OpenSun,
                    OpenThu = model.OpenThu,
                    OpenTue = model.OpenTue,
                    OpenWed = model.OpenWed,
                    Phone = model.Phone,
                    StoreName = model.StoreName,
                    Street = model.Street,
                    ZipCode = model.ZipCode,
                };

                await storeRepository.EditStore(store);
                return RedirectToAction("Details", new { id = model.Id });
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await storeRepository.GetStore(id);
            if (result == null)
            {
                ViewBag.ErrorMessage = $"Store with Id = {id} cannot be found";
                return View("NotFound"); 
            }
            else
            {
                await storeRepository.DeleteStore(id);
                return RedirectToAction("Index");
            }
        }
    }
}

LunchBoxAdmin/Controllers/UserController.cs
using LunchBox.Shared;
using LunchBoxAdmin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LunchBoxAdmin.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly UserManager<User> userManager;

        public UserController(UserManager<User> userManager)
        {
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            var users = userManager.Users;

            return View(users);
        }
    }
}

LunchBoxAdmin/Views/Shared/NotFound.cshtml
@{
    ViewBag.ErrorTitle = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="index" asp-controller="home">
    Click here to navigate to the home page
</a>

LunchBoxAdmin/Views/Shared/_ApplicationHeaderStylesPartial.cshtml
<environment include="Development">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootswatch-flatly/flatly/bootstrap.css" rel="stylesheet" />
</environment>
<environment exclude="Development">    
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous"
          asp-fallback-href="~/lib/bootswatch-flatly/flatly/bootstrap.min.css"
          asp-fallback-test-class="sr-only"
          asp-fallback-test-property="position"
          asp-fallback-test-value="absolute"
          asp-suppress-fallback-integrity="true"
    >
</environment>
<link rel="stylesheet" href="~/css/site.css" />

LunchBoxAdmin/Views/Shared/_Layout.cshtml
@inject SignInManager<LunchBox.Shared.User> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - LunchBox - Admin</title>
    @await Html.PartialAsync("_ApplicationHeaderStylesPartial")
</head>
<body>
    <header>
        @await Html.PartialAsync("_RenderMenuPartial", signInManager)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LunchBox - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @await Html.PartialAsync("_UScriptsPartial")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LunchBoxAdmin/Views/Shared/_RenderMenuPartial.cshtml
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark" style="margin-bottom: 20px;">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                @if (Model.IsSignedIn(User))  //@if (Context.Session.GetString("username") != null)
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Store" asp-action="Index">Stores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Index">Proucts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="ProductExtra" asp-action="Index">Product Items</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Administration" asp-action="Index">Admin</a>
                    </li>
                    <li class="nav-item">
                        <form method="post" asp-action="logout" asp-controller="account">
                            <button type="submit" class="nav-link btn btn-link py-0 logout-link" style="width:auto">Logout @User.Identity.Name</button>
                        </form>
                    </li>
                }else
                {
                    @*if (Context.Request.Path.Value.StartsWith("/Login") == false)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                    }*@
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="Home" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="login" asp-controller="account" class="nav-link">Login</a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="register" asp-controller="account" class="nav-link">Register</a>
                    </li>
                }
            </ul>
            @if (Model.IsSignedIn(User))
             {
                <form class="d-flex">
                    <input class="form-control me-sm-2" type="search" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
             }
        </div>
    </div>
</nav>

LunchBoxAdmin/Views/Shared/_UScriptsPartial.cshtml
<environment include="Development">
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
</environment>
<environment exclude="Development">
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
</environment>
<script src="~/js/site.js" asp-append-version="true"></script>